import React, { useCallback, useEffect, useState } from "react";
import { View, Text, FlatList, StyleSheet, TouchableOpacity, ActivityIndicator, Alert, useColorScheme } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { listarUsuarios } from "../service/usuario/usuarios";

export default function Usuarios({ navigation }) {
  const dark=useColorScheme()==="dark"; const [usuarios,setUsuarios]=useState([]); const [loading,setLoading]=useState(true); const [erro,setErro]=useState("");
  const carregar=useCallback(async()=>{try{setLoading(true);setErro("");setUsuarios(await listarUsuarios())}catch(e){setErro(e.message||"Não foi possível listar os usuários.")}finally{setLoading(false)}},[]);
  useEffect(()=>{carregar()},[carregar]);
  if(loading)return <View style={[styles.center,dark&&styles.dark]}><ActivityIndicator size="large" color="#0066B3"/></View>;
  return <View style={[styles.container,dark&&styles.dark]}><View style={styles.top}><View><Text style={[styles.title,dark&&styles.white]}>Usuários</Text><Text style={[styles.sub,dark&&styles.gray]}>Visualização dos usuários cadastrados</Text></View><TouchableOpacity style={styles.add} onPress={()=>navigation.navigate("Cadastro")}><Ionicons name="person-add" size={20} color="#fff"/></TouchableOpacity></View>{erro?<Text style={[styles.error,dark&&styles.white]}>{erro}</Text>:<FlatList data={usuarios} keyExtractor={(item,i)=>String(item.id??item.email??i)} renderItem={({item})=><TouchableOpacity style={[styles.item,dark&&styles.itemDark]} onPress={()=>navigation.navigate("Cadastro",{usuario:item})}><View style={styles.avatar}><Ionicons name="person" size={20} color="#fff"/></View><View style={{flex:1}}><Text style={[styles.name,dark&&styles.white]}>{item.nome||"Sem nome"}</Text><Text style={[styles.email,dark&&styles.gray]}>{item.email||"Sem e-mail"}</Text></View><Ionicons name="eye-outline" size={22} color="#0066B3"/></TouchableOpacity>} ListEmptyComponent={<Text style={[styles.empty,dark&&styles.white]}>Nenhum usuário encontrado.</Text>} />}</View>;
}
const styles=StyleSheet.create({container:{flex:1,padding:18,backgroundColor:"#f5f5f5"},dark:{backgroundColor:"#121212"},center:{flex:1,alignItems:"center",justifyContent:"center"},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:18},title:{fontSize:30,fontWeight:"800",color:"#222"},sub:{color:"#777",marginTop:3},gray:{color:"#aaa"},white:{color:"#fff"},add:{width:42,height:42,borderRadius:21,backgroundColor:"#0066B3",alignItems:"center",justifyContent:"center"},item:{backgroundColor:"#fff",borderRadius:14,padding:14,marginBottom:10,flexDirection:"row",alignItems:"center",gap:12},itemDark:{backgroundColor:"#1e1e1e"},avatar:{width:42,height:42,borderRadius:21,backgroundColor:"#0066B3",alignItems:"center",justifyContent:"center"},name:{fontSize:16,fontWeight:"800",color:"#222"},email:{color:"#666",marginTop:3},empty:{textAlign:"center",marginTop:50,color:"#444"},error:{textAlign:"center",marginTop:30,color:"#444"}});
